GET http://localhost:1234/customer
#######

POST http://localhost:1234/customer
Content-Type: application/json

{
  "name": "jhon doe",
  "document": "123456783",
  "email": "john.doe@example.com",
  "phone": "123-456-7890",
  "radicado": "12345678122",
  "type_document":"cc"
}


